### ISSUE TITLE
Browse Animations Tab Responsiveness Issue

### ISSUE THREAD

**Issue by ManedCalico** [TheLogicMaster/SDH-AnimationChanger#35]
Hello,

I'm having a few issues related to the "Browse Animations" tab. The tab is very slow to load, move away from, or navigate around. Unfortunately, the worst issue I'm running into is with the "Search Animations" keyboard. Once the keyboard opens, typing on it is incredibly difficult to the point of being unusable. Touch works alright if I go slowly, but using the trackpads is impossible.

I've tried reinstalling the plugin, but the behavior is the same. I was wondering if there's something else I could do or try, or if this was possibly a known issue?

Thanks

**Comment by ManedCalico** [comment]
Oh yikes! I was starting to notice it was getting worse over time, so I suspected this might be the case. Hopefully it's not too much of a headache to solve!

**Comment by TheLogicMaster** [comment]
Fixed with 1.3.0

**Comment by ManedCalico** [comment]
Thank you!

**Comment by Abbin44** [comment]
I downloaded version 1.3.0 and the issue still seems to be present. I waited for 5 minutes for it to load but it was still not showing any objects in the browser.

**Comment by Butanediol** [comment]
> I downloaded version 1.3.0 and the issue still seems to be present. I waited for 5 minutes for it to load but it was still not showing any objects in the browser.

Yeah I have the same issue here.
I'm on SteamOS 3.4.6, Decky Loader 2.7 and animation changer 1.3.

**Comment by TheLogicMaster** [comment]
> > I downloaded version 1.3.0 and the issue still seems to be present. I waited for 5 minutes for it to load but it was still not showing any objects in the browser.
> 
> Yeah I have the same issue here. I'm on SteamOS 3.4.6, Decky Loader 2.7 and animation changer 1.3.

It's probably the networking issue that has been mentioned in issues previously. The `Force IPv4` option in the quick access menu may help. An error may show in the log file at `/tmp/animation_changer.log`, but the current logging and front-end error handling may not be sufficient.

**Comment by ManedCalico** [comment]
It's been working for me without any issues since update 1.3.0 so I'm going to go ahead an close this. Thanks!

**Comment by Songkeys** [comment]
This still happens to me.

> The Force IPv4 option in the quick access menu may help.

I can't change any option correctly. After switching this option (and others) on, I went back, clicked in and saw all the option go back to the default again.
